version: "3.9"
services:
  http-auth:
    build: ./http-auth
    ports:
      - 3000:3000
    environment:
      - HTTP_AUTH_PORT=3000
    container_name: http-auth

  vmq:
    build: ./vmq
    ports:
     - 800:800       # WS 
     - 880:880       # WSS
     - 1883:1883     # MQTT
     - 8883:8883     # MQTT/SSL
     - 8888:8888     # HTTP
     - 44053:44053   # VMQ Clustering
    environment:
      - VMQ_HTTP_AUTH_URL=http://http-auth:3000/vmq/lua
    container_name: vmq
